version: 2.1
jobs:
  plan:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Archive repositories (dry run)
          command: node archive-all.js

  apply:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Archive repositories
          command: node archive-all.js
          environment:
            FOR_REAL: true

workflows:
  version: 2
  execute:
    jobs:
      - plan:
          filters:
            branches:
              ignore:
                - master
      - apply:
          filters:
            branches:
              only:
                - master
