version: 2.1
jobs:
  build:
    parameters:
      apply:
        type: boolean
        default: false
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm test

      - run:
          name: "Archive repositories (apply: << parameters.apply >>)"
          command: node cli.js archive <<# parameters.apply >>--apply<</ parameters.apply >>
      - run:
          name: "Enable security alerts (apply: << parameters.apply >>)"
          command: node cli.js enable-security-alerts <<# parameters.apply >>--apply<</ parameters.apply >>
      - run:
          name: "Enable security fixes for PIFs (apply: << parameters.apply >>)"
          command: node cli.js enable-security-fixes --org presidential-innovation-fellows <<# parameters.apply >>--apply<</ parameters.apply >>

workflows:
  version: 2
  pushes:
    jobs:
      # "plan" vs. apply
      - build:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              only:
                - master
          apply: true
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          apply: true
