version: 2.1
jobs:
  build:
    parameters:
      apply:
        type: boolean
        default: false
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: "Archive repositories (apply: << parameters.apply >>)"
          command: node index.js archive <<# parameters.apply >>--apply<</ parameters.apply >>

workflows:
  version: 2
  execute:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              only:
                - master
          apply: true
