---

name: Issues

on:
  issues:
    types: [opened]

jobs:
  issue_created:
    name: Add new issue to project board
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: TTS Technology Portfolio
          column: New
          repo-token: ${{ secrets.GH_PROJECT_WORKFLOW_TOKEN }}
