---

name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  pr_created:
    name: Add pull request to PR board
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: TTS Tech Portfolio (Pull Requests)
          column: Review required
          repo-token: ${{ secrets.GH_PROJECT_WORKFLOW_TOKEN }}
